name: ci


on:
  push:
    branches:
      - master

jobs:
  deploy-service:
    runs-on: ubuntu-latest

    steps:
      - name: git pull
        uses: fifsky/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          pass: ${{ secrets.SSH_PASS }}
          command: |
            cd /var/www/www-root/data/www/bizzon-shop.by/sochi
            git add . && git commit -m "auto commit"
            ${{ secrets.SCRIPT }}
      - name: install packages
        uses: fifsky/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          pass: ${{ secrets.SSH_PASS }}
          command: |
            cd /var/www/www-root/data/www/bizzon-shop.by/sochi
            yarn install
            apt-get install wget
            wget -O cars.json https://booking.autopilot.rent/api/sun/cars/getSeo/sochi.json
            wget -O news.json https://booking.autopilot.rent/api/sun/newsListSeo/sochi.json
            wget -O long.json https://booking.autopilot.rent/sun/sun-long-make-seo/sochi
            wget -O events.json https://booking.autopilot.rent/sun/sun-events-make-seo/sochi
            wget -O static/sitemap.xml https://booking.autopilot.rent/sun/sun-sites-sitemap/sochi
            wget -O static_booking.json https://booking.autopilot.rent/sun/sun-static-cars-sync/sochi
      - name: build
        uses: fifsky/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          pass: ${{ secrets.SSH_PASS }}
          command: |
            cd /var/www/www-root/data/www/bizzon-shop.by/sochi
            npm run build && npm run generate
            pm2 restart sochi
